In [1]:
import numpy as np
import math

In [2]:
i = 0
j = 0
d = 1.0
a = np.array([3/2,np.math.sqrt(3)/2])*d*(i-1)
b = np.array([-3/2,np.math.sqrt(3)/2])*d*(j-1)


In [3]:
print(a)

[-1.5       -0.8660254]


In [4]:
print(b)

[ 1.5       -0.8660254]


In [5]:
print(a+b+np.array([0,np.math.sqrt(3)]))

[0. 0.]


In [6]:
print(np.array([[1,3],[3,0]]))

[[1 3]
 [3 0]]


In [7]:
class MyBeeBot():
    def __init__(self):
        self.direction = 0  # intial degrees
        self.d = 0
        self.a_i = np.array([0,0])
    def numbers_to_action(self,argument): #affect ot a_i,a_j
        switcher = {
            0: 0,
            1: 1,
            2: -1,
            3: 60,
            4: [-1,0],
            5: -60,
        }
        return switcher.get(argument, "nothing")
    def numbers_to_direction(self,argument): #affect ot a_i,a_j
        switcher = {
            0: [1,1],
            1: [0,1],-5: [0,1],#60 degrees
            2: [-1,0],-4: [-1,0],#120 egrees
            3: [-1,-1],-3: [-1,-1],#180 degrees
            4: [0,-1],-2: [0,-1],#240 degrees
            5: [1,0],-1: [1,0],#300 degrees
        }
        return switcher.get(argument, "nothing")
    def stash_direction(self,degrees):
        self.direction += degrees 
        degrees = 0
        return self.direction
    def trackBeebot(self):
        # a = self.numbers_to_direction(3)
        a = self.stash_direction(-60)
        return a

In [8]:

A = MyBeeBot()
for i in range(0,10,1):
    action = A.numbers_to_action(3) #look action
    print(A.a_i)
    A.direction += action
    A.d = ((A.direction/60)%6)*(action/60) #find direction
    action = 0 # reset degrees 
    a_direction = np.array(A.numbers_to_direction(A.d))#เตรียมเดิน
    # print(A.direction,a_direction)
    actionV = np.array(A.numbers_to_action(1)) #look action
    A.a_i = A.a_i + (a_direction*actionV)
    print(a_direction,A.a_i,(actionV))




[0 0]
[0 1] [0 1] 1
[0 1]
[-1  0] [-1  1] 1
[-1  1]
[-1 -1] [-2  0] 1
[-2  0]
[ 0 -1] [-2 -1] 1
[-2 -1]
[1 0] [-1 -1] 1
[-1 -1]
[1 1] [0 0] 1
[0 0]
[0 1] [0 1] 1
[0 1]
[-1  0] [-1  1] 1
[-1  1]
[-1 -1] [-2  0] 1
[-2  0]
[ 0 -1] [-2 -1] 1


In [9]:
a = [1,2]
b = [5,3]
c = [a[0]+b[0],a[1]+b[1]]
# print(list(map(lambda x,y: [x[0]+y[0],x[1]+y[1]],a,b)))
print(c)

[6, 5]


In [10]:
# from trackbeebot import BeeBot
# class MyBeeBot(BeeBot):
#     def __init__(self,a_i):
#         super().__init__(a_i)
#         self.a_i = a_i
#         self.d = 1.0
#         self.direction = 0 # intial degrees
#     def stash_direction(self,degrees):
#         self.direction += degrees
#         return self.direction
#     def numbers_to_action(argument):
#         A=MyBeeBot(BeeBot) 
#         switcher = {
#             0: "stop",
#             1: "forward",
#             2: "backward",
#             3: A.stash_direction(60),
#             4: A.stash_direction(-60),
#         }
#         return switcher.get(argument, "nothing")

In [11]:
# klaza = MyBeeBot() 
# gg = klaza.numbers_to_action(0)

In [12]:
a = 3.0
if a in [3,4]:
    print("gg")

gg


In [13]:
def numbers_to_direction(argument): #affect ot a_i,a_j
    switcher = {
        0: "unknow",
        1: "unknow",
        2: "unknow", 
        3: 60,
        -4: [-1,0],
        5: 60,
    }
    return switcher.get(argument, "nothing")

In [14]:
print(numbers_to_direction(-4))

[-1, 0]


In [15]:
for i in range(0,10,1):
    if i>=5:
        print("ok")
    else:
        print("ko")

ko
ko
ko
ko
ko
ok
ok
ok
ok
ok


In [16]:
import numpy as np
import math
a = 2
b = [1, 1, 2 ,1, 1]
ar = np.array(a)
ag = np.array(b)
# print (ag*ar)
x_1 = (np.math.sqrt(3)/2)*ar
x_2 = (np.array(1/2))*ag
print (x_1,x_2)

1.7320508075688772 [0.5 0.5 1.  0.5 0.5]


In [17]:
print(list([1,2]))

[1, 2]


In [51]:


c= list([[],[]])
for i in range(0,5,1):
    m=float((-1)*(np.math.sqrt(3))) #transtorm pos2scaleG
    n=float((3)*(np.math.sqrt(3))) #transtorm pos2scaleG
    x = ((np.math.sqrt(3)/2)*m)-((np.math.sqrt(3)/2)*n)
    y = (((1/2)*m)+((1/2)*n))
    # c += [x]
    c[1] += [float(x)]
    c[0] += [float(x)]
    # print([a]+[b])
    z = np.array(c)
print(c)
   







[[-6.0, -6.0, -6.0, -6.0, -6.0], [-6.0, -6.0, -6.0, -6.0, -6.0]]


In [19]:
a = [1,3]
b = [3,6]
x = np.array([1,3])
y = np.array([-3,6])
print(a+b) #no array
print(x+y) #array variable
print(np.array(a+b)) # array list


[1, 3, 3, 6]
[-2  9]
[1 3 3 6]


In [20]:
import json
with open('testcase.json') as f:
    lines = f.readlines()
testcases = json.loads(lines[0])
i = 1
for testcase in testcases["testcase"]:
    W = np.array(testcase["w"])
    wall = list(map(lambda x,y: [x,y],W[0],W[1]))
    print(W)
    print(wall,type(wall))
    if [0,0] in wall:
        print('kla')
    break

[[-1  0 -2  0 -4  2  5 -2  2  1  4  2 -2 -4]
 [ 1  0 -1  5  2  2  1 -4 -5  1 -5 -1  4  0]]
[[-1, 1], [0, 0], [-2, -1], [0, 5], [-4, 2], [2, 2], [5, 1], [-2, -4], [2, -5], [1, 1], [4, -5], [2, -1], [-2, 4], [-4, 0]] <class 'list'>
kla


In [52]:

d = ((300/60)%6)*(60/60)
print(d)

5.0


In [64]:
# round(1.2 / 0.2)
a = (1.2 / 0.2)
b = np.array([[a],[a],[a],[a]])
print(b)
print(type(b))

[[6.]
 [6.]
 [6.]
 [6.]]
<class 'numpy.ndarray'>
