In [58]:
import math
import re 
import numpy as np
Tra_x   = [[1.,0.,0.,1.],
                    [0.,1.,0.,0.],
                    [0.,0.,1.,0.],
                    [0.,0.,0.,1.]]


In [59]:
print(Tra_x[0][3],"\n","klaza")

1.0 
 klaza


In [84]:
joint = 3
def forward_kin(q):
    DH_table = ([[0,0,0.3,0.],
                [0.16,math.pi/2,0.,0.],
                [0.35,0.,0.,0.]])
    P = [1,1,1]
    H = np.identity(4)

    H3_e = [[0.,0.,1.,0.16],
                    [1.,0.,0.,0.],
                    [0.,-1.,0.,0.],
                    [0.,0.,0.,1.]]

    for i in range(0,joint):
        Tx = DH_table[i][0] 
        Rx = DH_table[i][1] 
        Tz = DH_table[i][2] 
        Rz = DH_table[i][3] 
        Tra_x   = [[1.,0.,0.,Tx],
                [0.,1.,0.,0.],
                [0.,0.,1.,0.],
                [0.,0.,0.,1.]]

        Rot_x   = [[1.,0.,0.,0.],
                [0.,math.cos(Rx),-1*math.sin(Rx),0.],
                [0.,math.sin(Rx),math.cos(Rx),0.],
                [0.,0.,0.,1.]]
                            
        Tra_z   = [[1.,0.,0.,0.],
                [0.,1.,0.,0.],
                [0.,0.,1.,Tz],
                [0.,0.,0.,1.]]
        Rot_z   = [[math.cos(Rz),-1*math.sin(Rz),0.,0.],
                [math.sin(Rz),math.cos(Rz),0.,0.],
                [0.,0.,1.,0.],
                [0.,0.,0.,1.]]

        if P[i] == 1:
            # print(q[i])
            Rot_z_q   = [[math.cos(q[i]),-1*math.sin(q[i]),0.,0.],
                        [math.sin(q[i]),math.cos(q[i]),0.,0.],
                        [0.,0.,1.,0.],
                        [0.,0.,0.,1.]]
            Hj = Rot_z_q
        else:
            Tra_z_q   = [[1.,0.,0.,0.],
                        [0.,1.,0.,0.],
                        [0.,0.,1.,q[i]],
                        [0.,0.,0.,1.]]
            Hj = Tra_z_q

        H = H @ Tra_x @ Rot_x @ Tra_z @ Rot_z @ Hj
        # print(H)
    H0_e = H@H3_e
#     print(Tra_x,"\n",Rot_x,"\n",Tra_z,"\n",Rot_z)
    return H0_e

def forward_kinematics(q):
    joint_config = q
    n_joint = 3
    DH_pam = [[0 ,0 ,0.3 ,0],
              [0.16 ,math.pi/2 ,0 ,0],
              [0.35 ,0 ,0 ,0]]

    H = np.identity(4)

    H_end_eff = [[0 , 0 ,1 ,0.16],
                 [1 , 0 ,0 ,0],
                 [0 ,1 ,0 ,0],
                 [0 , 0 ,0 ,1]]

    for i in range(joint):
        rad = joint_config[i]
        c ,s = np.cos(rad), np.sin(rad)
        c_x ,s_x = np.cos(DH_pam[i][1]), np.sin(DH_pam[i][1])
        c_z ,s_z = np.cos(DH_pam[i][3]), np.sin(DH_pam[i][3])

        T_x =  [[1 ,0 ,0 ,DH_pam[i][0]],               
                [0 ,1 ,0 ,0],
                [0 ,0, 1 ,0],
                [0 ,0 ,0 ,1]]

        R_x =  [[1 ,   0 ,   0 ,0],           
                [0 , c_x ,-s_x ,0],
                [0 , s_x , c_x ,0],
                [0 ,   0 ,   0 ,1]]

        T_z =  [[1 ,0 ,0 ,0],
                [0 ,1 ,0 ,0],
                [0 ,0 ,1 ,DH_pam[i][2]],
                [0 ,0 ,0 ,1]]

        R_z =  [[c_z ,-s_z ,0 ,0],
                [s_z , c_z ,0 ,0],
                [0   ,   0 ,1 ,0],
                [0   ,   0 ,0 ,1]]

        H_j =  [[c ,-s ,0 ,0],
                [s , c ,0 ,0],
                [0 , 0 ,1 ,0],
                [0 , 0 ,0 ,1]]

        H = H @ T_x @ R_x @ T_z @ R_z @ H_j      
        # print(H)
    H = H@H_end_eff
#     print(T_x,"\n",R_x,"\n",T_z,"\n",T_z)

    return H

In [88]:
a = forward_kin([3.14,1.57,1.57])
b = forward_kinematics([3.14,1.57,1.57])
print(a,"\n",b)

[[ 1.59265090e-03 -1.59265292e-03  9.99997463e-01 -2.78916919e-04]
 [-2.53654331e-06 -9.99998732e-01 -1.59265090e-03  4.44218407e-07]
 [-9.99998732e-01 -6.12323400e-17  1.59265292e-03  6.50254713e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]] 
 [[ 1.59265090e-03  1.59265292e-03  9.99997463e-01 -2.78916919e-04]
 [-2.53654331e-06  9.99998732e-01 -1.59265090e-03  4.44218407e-07]
 [-9.99998732e-01  6.12323400e-17  1.59265292e-03  6.50254713e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [79]:
for i in range(0,3):
    # print(i)
    A = [1,2,3]
    print(A[i])

1
2
3
